include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_CONTACT alex@gmail.com)
set(CPACK_PACKAGE_VERSION ${PRINT_VERSION})
set(CPACK_PACKAGE_NAME "main")
set(CPACK_PACKAGE_VENDOR "alex")
set(CPACK_PACKAGE_PACK_NAME "main-${PRINT_VERSION}")

set(CPACK_SOURCE_INSTALLED_DIRECTORIES 
	"${CMAKE_SOURCE_DIR}/main; main"
	"${CMAKE_SOURCE_DIR}/tests; tests")

set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")

set(CPACK_DEBIAN_PACKAGE_VERSION ${PRINT_VERSION})
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "all")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "logger")

set(CPACK_GENERATOR "DEB;RPM")

set(CPACK_RPM_PACKAGE_SUMMARY "logger")

include(CPack)
